name: note_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  provider: ^6.1.2
  google_fonts: ^6.2.1
  popover: ^0.3.0+1
  http: ^1.2.1
  lottie: ^3.1.2
  introduction_screen: ^3.1.14
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.10

flutter_icons:
  image_path: "icons/icon_app.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
 